### PR TITLE
Replace Varela with Muli, remove Vollkorn

### PR DESCRIPTION
**Pull request by bendansby**

### CODE REVIEW

**Review by tesk9 — APPROVED** [review]
🎉

**Comment by blunderdome** [comment]
Last time we tried a font change there were loads of visual bugs. This should go through a separate QA pass. Not sure what that entails since this is a separate repo.

**Comment by tesk9** [comment]
@blunderdome the actual changes will be in master once https://github.com/NoRedInk/NoRedInk/pull/15157 and https://github.com/NoRedInk/NoRedInk/pull/15160.

Should @bendansby schedule a QA for those two branches?

**Comment by blunderdome** [comment]
Yes please :+1:

**Comment by bendansby** [comment]
Is there a guide for how to schedule QA time?

**Comment by tesk9** [comment]
There are instructions here:
https://github.com/NoRedInk/wiki/blob/master/qa/requesting-special-qa.md

**Pull request merged**
