### PR TITLE
Color corrections/updates

### PR DESCRIPTION
**Pull request by allymcknight**
Corrected Azure and grey96.

### CODE REVIEW

**Comment by bendansby** [comment]
Cool! Anything else that still needs doing from here is fair game.
color transposition 2

**Review by tesk9 — COMMENTED** [review]
Coupla questions!

1. Was the invision I linked you to wrong? Or were these typos?
2. Why 2.0.1 -> 2.1.1?

**Comment by allymcknight** [comment]
@tesk9 Both! I had a typo on the Azure and the gray was wrong on the invision. So this is a 2 birds with one stone update.

The elm package bump just told me that was the new version...

**Comment by tesk9** [comment]
Ahh okay I understand what's a'happenin'.

I was confused because 2.0.1 -> 2.1.1 signals a minor change rather than a patch bug fix (http://semver.org/) which this seemed like.

The last time we published nri-elm-css, the version was v 2.1.0. That actually was a MINOR change because we added new colors, but we didn't remove any old colors. But, github ended up behind on the versioning. (notice the version number here: http://package.elm-lang.org/packages/NoRedInk/nri-elm-css/latest).

Try running elm-package bump one more time. We should have a patch change.

**Comment by tesk9** [comment]
cc @allymcknight

**Pull request merged**
