### PR TITLE
Delete Indie Flower, delete Rubik

### PR DESCRIPTION
**Pull request by bendansby**

### CODE REVIEW

**Comment by avh4** [comment]
This is going to be a major version bump because we're removing exposed definitions.

I'm going to remove the version bump commits and bump it when we publish the next version.

**Review by avh4 — APPROVED** [review]

**Comment by stoeffel** [comment]
Is there a PR in place to change `indieFlowerFont` here => https://github.com/NoRedInk/NoRedInk/blob/77cfdaa3f092e016a47a14ca91cc896d448a95ab/ui/src/Nri/SplashPage/Styles.elm#L102-L106.
What font should we use there?

**Comment by bendansby** [comment]
@stoeffel Yep https://github.com/NoRedInk/NoRedInk/pull/15435

**Pull request merged**
