### PR TITLE
Add flexbox vendor prefixes

### PR DESCRIPTION
**Pull request by cachar**
Adds vendor prefixes for cross browser support of flexbox.

### CODE REVIEW

**Comment by eeue56** [comment]
Should this go to elm-css instead?

**Comment by rtfeldman** [comment]
I've thought about that and I don't think it makes sense in the core
elm-css library. It won't work consistently with inline styles vs not, and
I don't really want to get into discussions of when it's appropriate to
prefix vs not.

Luke was working on an autoprefixer transform but I don't think he got
especially close to finishing it.

**Comment by eeue56** [comment]
fwiw we can do proper, non inline styles now using marica's approach to webpacking asssets. which means we can get autoprefixer working

**Comment by rtfeldman** [comment]
That sound awesome! 😻 

Love it!

**Comment by rtfeldman** [comment]
Here's Luke's repo, for reference: https://github.com/lukewestby/elm-css-autoprefix

**Comment by eeue56** [comment]
@cachar why'd you close it?

**Comment by cachar** [comment]
I assumed from this conversation that we were going to have an autoprefixer, and that this update was irrelevant. This code is currently duplicated in our main repo anyway. Happy to reopen if that's not the case.

**Pull request closed without merging**
